In [1]:
!pip install scikit-learn


[notice] A new release of pip is available: 23.2.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import matplotlib as plt
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score,recall_score,f1_score

In [5]:
heart=pd.read_csv("heart.csv")

In [6]:
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [8]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [9]:
heart.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [12]:
X=heart.drop("target",axis=1)
Y=heart["target"]

In [13]:
numerical_data=X.select_dtypes(exclude=['object']).columns

In [14]:
numerical_data

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

In [16]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X[numerical_data]=pd.DataFrame(scaler.fit_transform(X[numerical_data]))

In [17]:
X

age       sex        cp  trestbps      chol       fbs   restecg  \
0    -0.268437  0.661504 -0.915755 -0.377636 -0.659332 -0.418878  0.891255   
1    -0.158157  0.661504 -0.915755  0.479107 -0.833861  2.387330 -1.004049   
2     1.716595  0.661504 -0.915755  0.764688 -1.396233 -0.418878  0.891255   
3     0.724079  0.661504 -0.915755  0.936037 -0.833861 -0.418878  0.891255   
4     0.834359 -1.511706 -0.915755  0.364875  0.930822  2.387330  0.891255   
...        ...       ...       ...       ...       ...       ...       ...   
1020  0.503520  0.661504  0.055931  0.479107 -0.484803 -0.418878  0.891255   
1021  0.613800  0.661504 -0.915755 -0.377636  0.232705 -0.418878 -1.004049   
1022 -0.819834  0.661504 -0.915755 -1.234378  0.562371 -0.418878 -1.004049   
1023 -0.488996 -1.511706 -0.915755 -1.234378  0.155137 -0.418878 -1.004049   
1024 -0.047877  0.661504 -0.915755 -0.663216 -1.124743 -0.418878  0.891255   

       thalach     exang   oldpeak     slope        ca      thal  
0     0.821321 -0.712287 -0.060888  0.995433  1.209221  1.089852  
1     0.255968  1.403928  1.727137 -2.243675 -0.731971  1.089852  
2    -1.048692  1.403928  1.301417 -2.243675 -0.731971  1.089852  
3     0.516900 -0.712287 -0.912329  0.995433  0.238625  1.089852  
4    -1.874977 -0.712287  0.705408 -0.624121  2.179817 -0.522122  
...        ...       ...       ...       ...       ...       ...  
1020  0.647366  1.403928 -0.912329  0.995433 -0.731971 -0.522122  
1021 -0.352873  1.403928  1.471705 -0.624121  0.238625  1.089852  
1022 -1.353113  1.403928 -0.060888 -0.624121  0.238625 -0.522122  
1023  0.429923 -0.712287 -0.912329  0.995433 -0.731971 -0.522122  
1024 -1.570556 -0.712287  0.279688 -0.624121  0.238625  1.089852  

[1025 rows x 13 columns]

In [18]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=40)

In [19]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [20]:
y_pred=model.predict(x_test)

In [21]:
y_pred

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0])

In [23]:
y_test.values

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0])

In [25]:
acc=accuracy_score(y_pred,y_test)
con_mat=confusion_matrix(y_pred,y_test)
report=classification_report(y_pred,y_test)

In [32]:
print("Accuracy: {:.2f}%".format(acc*100))

Accuracy: 81.46%


In [34]:
con_mat

array([[79, 14],
       [24, 88]])

In [36]:
print(report)

              precision    recall  f1-score   support

           0       0.77      0.85      0.81        93
           1       0.86      0.79      0.82       112

    accuracy                           0.81       205
   macro avg       0.81      0.82      0.81       205
weighted avg       0.82      0.81      0.82       205

